### ISSUE TITLE
How to obtain exactly config.yaml?

### ISSUE THREAD

**Issue by pedrobagatin** [xdspacelab/openvslam#110]
I did [monocular calibration](http://wiki.ros.org/camera_calibration/Tutorials/MonocularCalibration) however generated config.yaml is a little different from the examples:

os.txt
```
# oST version 5.0 parameters


[image]

width
640

height
480

[narrow_stereo]

camera matrix
1523.306037 0.000000 146.852037
0.000000 1380.330890 116.819146
0.000000 0.000000 1.000000

distortion
0.853147 0.038534 -0.060017 -0.116773 0.000000

rectification
1.000000 0.000000 0.000000
0.000000 1.000000 0.000000
0.000000 0.000000 1.000000

projection
1556.893188 0.000000 130.445498 0.000000
0.000000 1453.644043 109.946910 0.000000
0.000000 0.000000 1.000000 0.000000
```

And .yaml file:

```
image_width: 640
image_height: 480
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [1523.306037, 0.000000, 146.852037, 0.000000, 1380.330890, 116.819146, 0.000000, 0.000000, 1.000000]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [0.853147, 0.038534, -0.060017, -0.116773, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1.000000, 0.000000, 0.000000, 0.000000, 1.000000, 0.000000, 0.000000, 0.000000, 1.000000]
projection_matrix:
  rows: 3
  cols: 4
  data: [1556.893188, 0.000000, 130.445498, 0.000000, 0.000000, 1453.644043, 109.946910, 0.000000, 0.000000, 0.000000, 1.000000, 0.000000]
```
