### ISSUE TITLE
not accurate localization with openvslam

### ISSUE THREAD

**Issue by roboticsai** [xdspacelab/openvslam#485]
I am testing the openvslam slam and localization node with monocular camera. But when i view the [result](https://www.youtube.com/watch?v=1AoPQZgGIXM&t=89s) i saw that the robot is not localizing itself accurately in given map.
I did the camera calibration with ros camera calibration parameter.
```
image_width: 1280
image_height: 720
camera_name: camera
camera_matrix:
  rows: 3
  cols: 3
  data: [1332.107090741891, 0, 646.8646682329983, 0, 1283.553969935012, 355.9515438263148, 0, 0, 1]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.6490073621987695, -0.2343410863844743, -0.02115290462789926, 0.0202207718179566, 0]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1, 0, 0, 0, 1, 0, 0, 0, 1]
projection_matrix:
  rows: 3
  cols: 4
  data: [1331.066284179688, 0, 646.359274794886, 0, 0, 1281.771240234375, 355.4571682230744, 0, 0, 0, 1, 0]
```
